# H2 Database Configuration
#spring.datasource.url=jdbc:h2:mem:testdb
#spring.datasource.driverClassName=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=password
#spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Enable H2 Console
#spring.h2.console.enabled=true
#spring.h2.console.path=/h2-console

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/logistica_db}
spring.datasource.username=${DB_USER:postgres}

spring.datasource.password=${DB_PASSWORD:postgresql}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate Configuration
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true

# Dialecto específico para que aprovecha las funciones nativas de Postgres
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Actuator Configuration
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always

# DevTools Configuration
spring.devtools.restart.enabled=true

# Server Configuration for Dockerfile
server.port=${PORT:8080}

# Habilitar la exportación a Datadog
management.datadog.metrics.export.api-key=${DD_API_KEY:}
management.datadog.metrics.export.uri=${DD_URI:https://api.us3.datadoghq.com}
management.datadog.metrics.export.step=10s
management.datadog.metrics.export.descriptions=true
management.datadog.metrics.export.enabled=true
management.datadog.metrics.export.application-key=${DD_APP_KEY:}
management.datadog.metrics.export.tags.instancia=${DD_INSTANCIA:desconocida}

#Logistica
spring.application.name=logistica

# Tags globales para identificar el módulo en Datadog
management.metrics.tags.aplicacion=logistica
management.metrics.tags.ambiente=produccion

# ETIQUETA CLAVE: Así identificamos que esta métrica es de TU servicio
management.metrics.tags.application=donatrack-logistica

# URLs de los otros módulos para integración HTTP (flujos obligatorios)
donaciones.url=${DONACIONES_URL:http://localhost:8081}
donadoresyentidades.url=${DONADORESYENT_URL:http://localhost:8083}

#logging.level.io.micrometer.datadog=DEBUG

#swagger
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs

#RabbitMQ
spring.rabbitmq.addresses=${RABBITMQ_URL:amqp://localhost:5672}
